[tool.poetry]
name = "shelley"
version = "0.1.0"
description = "Check system integration"
authors = ["Carlos Mão de Ferro", "Tiago Cogumbreiro", "Francisco Martins"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
pyyaml = "^5.3.1"
graphviz = "^0.14"
karukuri = {git = "https://gitlab.com/cogumbreiro/karukuri.git", rev = "ad663048380a892f0290aa1605f164e881322e70"}

[tool.poetry.dev-dependencies]
mypy = "^0.770"
pytest = "^5.4.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
