[tool.poetry]
name = "shelley"
version = "0.1.7"
description = "Check system integration"
authors = ["Carlos Mão de Ferro", "Tiago Cogumbreiro", "Francisco Martins"]
license = "MIT"
readme = 'README.rst'

[tool.poetry.dependencies]
python = "^3.7"
pyyaml = "^5.3.1"
graphviz = "^0.14"
karukuri = {git = "https://gitlab.com/cogumbreiro/karukuri.git", rev = "51cdf034c085e493f0364f710e0a4601cb85f1b9"}

[tool.poetry.dev-dependencies]
mypy = "^0.770"
pytest = "^5.4.1"
black = "^19.10b0"
Pygments = "^2.6.1"
snakeviz="^2.1.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
shelleyc = "shelley.shelleyc.main:main"
shelleyv = "shelley.shelleyv.main:main"
