bad:
	$(MAKE) -C bad_ambiguity_aquamote_core_v4_boot scy
	$(MAKE) -C bad_ambiguity_v1 scy
	$(MAKE) -C bad_ambiguity_v2 scy
	$(MAKE) -C bad_ambiguity_v3 scy
	$(MAKE) -C bad_ambiguity_v4 scy
	$(MAKE) -C bad_ambiguity_v5 scy
	$(MAKE) -C bad_ambiguity_v6 scy
	$(MAKE) -C bad_ambiguity_v7 scy
	$(MAKE) -C bad_aquamote_core_v4_boot scy
	$(MAKE) -C bad_empty_body_all scy
	$(MAKE) -C bad_formed_undeclared_right_op scy
	$(MAKE) -C bad_hard_disk_integration scy
	$(MAKE) -C bad_integration scy
	$(MAKE) -C bad_integration_v1 scy
	$(MAKE) -C bad_integration_v2 scy
	$(MAKE) -C bad_integration_v3 scy
	$(MAKE) -C bad_paper_frankenstein_example_controller_sink scy
	$(MAKE) -C bad_paper_frankenstein_example_controller_sink_v2 scy
	$(MAKE) -C bad_paper_frankenstein_example_controller_unreachable scy
	$(MAKE) -C bad_parsing_unexpected_section_names scy
	$(MAKE) -C bad_system_no_start_event scy
	$(MAKE) -C bad_system_undeclared_subsystem_operations scy
	$(MAKE) -C bad_system_unusable_sink scy
	$(MAKE) -C bad_system_unusable_sink_v2 scy
	$(MAKE) -C bad_system_unusable_unreachable_not_sink scy
	$(MAKE) -C bad_system_unusable_unreachable_sink scy
	$(MAKE) -C bad_system_unused_component scy
	$(MAKE) -C bad_verdi_running_example_bad_sector scy
	$(MAKE) -C bad_vhandler_examples_python_loop scy

good:
	$(MAKE) -C 2controllers_v1_easy scy
	$(MAKE) -C 2controllers_v1_hard scy
	$(MAKE) -C 2controllers_v2_easy scy
	$(MAKE) -C 2controllers_v2_hard scy
	$(MAKE) -C 2controllers_v3_easy scy
	$(MAKE) -C 2controllers_v3_hard scy
	$(MAKE) -C aquamote_cpp_var2 scy
	$(MAKE) -C aquamote_cpp_var3 scy
	$(MAKE) -C aquamote_cpp_var4 scy
	$(MAKE) -C aquamote_v1 scy
	$(MAKE) -C aquamote_v2 scy
	$(MAKE) -C aquamote_v3 scy
	$(MAKE) -C aquamote_v4 scy
	$(MAKE) -C aquamote_v5 scy
	$(MAKE) -C aquamote_v6 scy
	$(MAKE) -C aquamote_v7 scy
	$(MAKE) -C aquamote_v8 scy
	$(MAKE) -C aquamote_v9 scy
	$(MAKE) -C base scy
	$(MAKE) -C blink scy
	$(MAKE) -C boatleds scy
	$(MAKE) -C clickbutton scy
	$(MAKE) -C desklamp scy
	$(MAKE) -C desklamp_nobutton scy
	$(MAKE) -C desklamp_simple scy
	$(MAKE) -C desklamp_simple2 scy
	$(MAKE) -C empty_body scy
	$(MAKE) -C empty_next scy
	$(MAKE) -C empty_next_base scy
	$(MAKE) -C force_usage scy
	$(MAKE) -C ledbutton scy
	$(MAKE) -C ledbuttonstrict scy
	$(MAKE) -C paper_aquamote scy
	$(MAKE) -C paper_frankenstein_example scy
	$(MAKE) -C paper_frankenstein_example_controller_not_sink scy
	$(MAKE) -C people_counter scy
	$(MAKE) -C pycontrol_reversal_learning scy
	$(MAKE) -C seven_leds scy
	$(MAKE) -C smartbutton scy
	$(MAKE) -C smartbutton_timer_double scy
	$(MAKE) -C smartbutton_timer_double_complex scy
	$(MAKE) -C smartbutton_timer_long scy
	$(MAKE) -C smartbutton_timer_single scy
	$(MAKE) -C smartled scy
	$(MAKE) -C smartled2 scy
	$(MAKE) -C thesis_aquamote_example scy
	$(MAKE) -C thesis_running_example_python scy
	$(MAKE) -C thesis_shelley_101 scy
	$(MAKE) -C trafficlight_gamma scy
	$(MAKE) -C trafficlight_gamma2 scy
	$(MAKE) -C trafficlight_gamma2_variant scy
	$(MAKE) -C trafficlight_gamma_fm scy
	$(MAKE) -C trafficlight_gamma_tc scy
	$(MAKE) -C trafficlight_gamma_timers scy
	$(MAKE) -C valve-too-long scy
	$(MAKE) -C valvehandlerNOloop_op1 scy
	$(MAKE) -C valvehandlerNOloop_op2 scy
	$(MAKE) -C valvehandlerloop scy
	$(MAKE) -C vhandler_examples_python_if_match_v1 scy
	$(MAKE) -C vhandler_examples_python_if_v1 scy
	$(MAKE) -C vhandler_examples_python_if_v2 scy
	$(MAKE) -C vhandler_examples_python_match_if_v1 scy
	$(MAKE) -C vhandler_examples_python_match_v1 scy
	$(MAKE) -C vhandler_examples_python_sequence_v1 scy
	$(MAKE) -C vhandler_examples_python_v3 scy
	$(MAKE) -C vhandler_examples_python_v4 scy

clean:
	$(MAKE) -C base clean
	$(MAKE) -C 2controllers_v1_easy clean
	$(MAKE) -C 2controllers_v1_hard clean
	$(MAKE) -C 2controllers_v2_easy clean
	$(MAKE) -C 2controllers_v2_hard clean
	$(MAKE) -C 2controllers_v3_easy clean
	$(MAKE) -C 2controllers_v3_hard clean
	$(MAKE) -C aquamote_cpp_var2 clean
	$(MAKE) -C aquamote_cpp_var3 clean
	$(MAKE) -C aquamote_cpp_var4 clean
	$(MAKE) -C aquamote_v1 clean
	$(MAKE) -C aquamote_v2 clean
	$(MAKE) -C aquamote_v3 clean
	$(MAKE) -C aquamote_v4 clean
	$(MAKE) -C aquamote_v5 clean
	$(MAKE) -C aquamote_v6 clean
	$(MAKE) -C aquamote_v7 clean
	$(MAKE) -C aquamote_v8 clean
	$(MAKE) -C aquamote_v9 clean
	$(MAKE) -C bad_ambiguity_aquamote_core_v4_boot clean
	$(MAKE) -C bad_ambiguity_v1 clean
	$(MAKE) -C bad_ambiguity_v2 clean
	$(MAKE) -C bad_ambiguity_v3 clean
	$(MAKE) -C bad_ambiguity_v4 clean
	$(MAKE) -C bad_ambiguity_v5 clean
	$(MAKE) -C bad_ambiguity_v6 clean
	$(MAKE) -C bad_ambiguity_v7 clean
	$(MAKE) -C bad_aquamote_core_v4_boot clean
	$(MAKE) -C bad_empty_body_all clean
	$(MAKE) -C bad_formed_undeclared_right_op clean
	$(MAKE) -C bad_hard_disk_integration clean
	$(MAKE) -C bad_integration clean
	$(MAKE) -C bad_integration_v1 clean
	$(MAKE) -C bad_integration_v2 clean
	$(MAKE) -C bad_integration_v3 clean
	$(MAKE) -C bad_paper_frankenstein_example_controller_sink clean
	$(MAKE) -C bad_paper_frankenstein_example_controller_sink_v2 clean
	$(MAKE) -C bad_paper_frankenstein_example_controller_unreachable clean
	$(MAKE) -C bad_parsing_unexpected_section_names clean
	$(MAKE) -C bad_system_no_start_event clean
	$(MAKE) -C bad_system_undeclared_subsystem_operations clean
	$(MAKE) -C bad_system_unusable_sink clean
	$(MAKE) -C bad_system_unusable_sink_v2 clean
	$(MAKE) -C bad_system_unusable_unreachable_not_sink clean
	$(MAKE) -C bad_system_unusable_unreachable_sink clean
	$(MAKE) -C bad_system_unused_component clean
	$(MAKE) -C bad_verdi_running_example_bad_sector clean
	$(MAKE) -C bad_vhandler_examples_python_loop clean
	$(MAKE) -C base clean
	$(MAKE) -C blink clean
	$(MAKE) -C boatleds clean
	$(MAKE) -C clickbutton clean
	$(MAKE) -C desklamp clean
	$(MAKE) -C desklamp_nobutton clean
	$(MAKE) -C desklamp_simple clean
	$(MAKE) -C desklamp_simple2 clean
	$(MAKE) -C empty_body clean
	$(MAKE) -C empty_next clean
	$(MAKE) -C empty_next_base clean
	$(MAKE) -C force_usage clean
	$(MAKE) -C ledbutton clean
	$(MAKE) -C ledbuttonstrict clean
	$(MAKE) -C paper_aquamote clean
	$(MAKE) -C paper_frankenstein_example clean
	$(MAKE) -C paper_frankenstein_example_controller_not_sink clean
	$(MAKE) -C people_counter clean
	$(MAKE) -C pycontrol_reversal_learning clean
	$(MAKE) -C seven_leds clean
	$(MAKE) -C smartbutton clean
	$(MAKE) -C smartbutton_timer_double clean
	$(MAKE) -C smartbutton_timer_double_complex clean
	$(MAKE) -C smartbutton_timer_long clean
	$(MAKE) -C smartbutton_timer_single clean
	$(MAKE) -C smartled clean
	$(MAKE) -C smartled2 clean
	$(MAKE) -C thesis_aquamote_example clean
	$(MAKE) -C thesis_running_example_python clean
	$(MAKE) -C thesis_shelley_101 clean
	$(MAKE) -C trafficlight_gamma clean
	$(MAKE) -C trafficlight_gamma2 clean
	$(MAKE) -C trafficlight_gamma2_variant clean
	$(MAKE) -C trafficlight_gamma_fm clean
	$(MAKE) -C trafficlight_gamma_tc clean
	$(MAKE) -C trafficlight_gamma_timers clean
	$(MAKE) -C valve-too-long clean
	$(MAKE) -C valvehandlerNOloop_op1 clean
	$(MAKE) -C valvehandlerNOloop_op2 clean
	$(MAKE) -C valvehandlerloop clean
	$(MAKE) -C vhandler_examples_python_if_match_v1 clean
	$(MAKE) -C vhandler_examples_python_if_v1 clean
	$(MAKE) -C vhandler_examples_python_if_v2 clean
	$(MAKE) -C vhandler_examples_python_match_if_v1 clean
	$(MAKE) -C vhandler_examples_python_match_v1 clean
	$(MAKE) -C vhandler_examples_python_sequence_v1 clean
	$(MAKE) -C vhandler_examples_python_v3 clean
	$(MAKE) -C vhandler_examples_python_v4 clean
