all:
	$(MAKE) -C desklamp/bad_desklamp1
	$(MAKE) -C desklamp/bad_desklamp_ambiguity1
	$(MAKE) -C desklamp/bad_desklamp_ambiguity2
	$(MAKE) -C desklamp/bad_desklamp_ambiguity3
	$(MAKE) -C desklamp/good_desklamp
	$(MAKE) -C desklamp/good_simple_desklamp
	$(MAKE) -C desklamp/good_simple_desklamp2
	$(MAKE) -C desklamp/smartled clean
	$(MAKE) -C buttons/bad_ambiguous
	$(MAKE) -C buttons/bad_ambiguous2
	$(MAKE) -C buttons/bad_missing_trigger
	$(MAKE) -C buttons/bad_smartbutton
	$(MAKE) -C buttons/bad_trigger_undeclared
	$(MAKE) -C buttons/good_ledbutton
	$(MAKE) -C buttons/good_ledbuttonstrict
	$(MAKE) -C buttons/bad_ledbuttonstrict
	$(MAKE) -C buttons/good_smartbutton
	$(MAKE) -C buttons/good_smartbutton_timer_double
	$(MAKE) -C buttons/good_smartbutton_timer_double_complex
	$(MAKE) -C buttons/good_smartbutton_timer_long
	$(MAKE) -C buttons/good_smartbutton_timer_single
	$(MAKE) -C aquamote/v1
	$(MAKE) -C aquamote/v2
	$(MAKE) -C aquamote/v2_finalstates
	$(MAKE) -C aquamote/v2_valve
	$(MAKE) -C aquamote/v2_valvehandler
	$(MAKE) -C aquamote/v2_valvehandlertimer
	#$(MAKE) -C aquamote/v3 --> TODO: FIX THIS
	$(MAKE) -C valves/1valve_complex
	$(MAKE) -C valves/1valve_seq
	#$(MAKE) -C valves/4valves_xorvsseq --> TODO: FIX THIS
	$(MAKE) -C valves/several_valves
	$(MAKE) -C valves/several_valves_integration
clean:
	$(MAKE) -C desklamp/bad_desklamp1 clean
	$(MAKE) -C desklamp/bad_desklamp_ambiguity1 clean
	$(MAKE) -C desklamp/bad_desklamp_ambiguity2 clean
	$(MAKE) -C desklamp/bad_desklamp_ambiguity3 clean
	$(MAKE) -C desklamp/good_desklamp clean
	$(MAKE) -C desklamp/good_simple_desklamp clean
	$(MAKE) -C desklamp/good_simple_desklamp2 clean
	$(MAKE) -C desklamp/smartled clean
	$(MAKE) -C buttons/bad_ambiguous clean
	$(MAKE) -C buttons/bad_ambiguous2 clean
	$(MAKE) -C buttons/bad_missing_trigger clean
	$(MAKE) -C buttons/bad_smartbutton clean
	$(MAKE) -C buttons/bad_trigger_undeclared clean
	$(MAKE) -C buttons/good_ledbutton clean
	$(MAKE) -C buttons/good_ledbuttonstrict clean
	$(MAKE) -C buttons/bad_ledbuttonstrict clean
	$(MAKE) -C buttons/good_smartbutton clean
	$(MAKE) -C buttons/good_smartbutton_timer_double clean
	$(MAKE) -C buttons/good_smartbutton_timer_double_complex clean
	$(MAKE) -C buttons/good_smartbutton_timer_long clean
	$(MAKE) -C buttons/good_smartbutton_timer_single clean
	$(MAKE) -C aquamote/v1 clean
	$(MAKE) -C aquamote/v2 clean
	$(MAKE) -C aquamote/v2_finalstates clean
	$(MAKE) -C aquamote/v2_valve clean
	$(MAKE) -C aquamote/v2_valvehandler clean
	$(MAKE) -C aquamote/v2_valvehandlertimer clean
	$(MAKE) -C aquamote/v3 clean
	$(MAKE) -C valves/1valve_complex clean
	$(MAKE) -C valves/1valve_seq clean
	$(MAKE) -C valves/4valves_xorvsseq clean
	$(MAKE) -C valves/several_valves clean
	$(MAKE) -C valves/several_valves_integration clean
